title: "Harsh Rawat"
email: "harsh.rawat17@gmail.com"
description: "Interested in the field of Analog and Digital VLSI design , with more experince in the analog side ."
baseurl: "/" 
url: "https://harshrawat17.github.io/" 
twitter_username: harshrawat17
github_username:  harshrawat17

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
