title: "Harsh Rawat"
email: harsh.rawat17@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://harshrawat17.github.io/" 
twitter_username: harshrawat17
github_username:  harshrawat17

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
