title: "Harsh Rawat"
email: "harsh.rawat17@gmail.com"
description: "Interested in the field of electronics and Analog design"
baseurl: "/" 
url: "https://harshrawat17.github.io/" 
twitter_username: harshrawat17
github_username:  harshrawat17
future: true
sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
